### ISSUE TITLE
Consider adding groovy-templates, groovy-xml, groovy-json

### ISSUE THREAD

**Issue by imagejan** [scijava/scripting-groovy#4]
To create powerful Groovy scripts in ImageJ, it would be useful to have `groovy-templates`, `groovy-xml` and `groovy-json` available on the classpath by default. How about adding them as `runtime` dependencies in this repository, and uploading them to the *Java-8* update site?

**Comment by ctrueden** [comment]
I added them, and uploaded them to the Java-8 update site as well. Please test.
